
import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ru' | 'zh';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.schedule": "Schedule",
    "nav.gallery": "Gallery",
    "nav.media": "Media",
    "nav.contact": "Contact",
    "media.title": "Media Library",
    "media.back": "Back to Library",
    "media.videos": "videos",
    "media.photos": "photos",
    "media.open": "Open Folder",
    "media.playlist": "Playlist",
    "media.folder.recordings.title": "Live Recordings",
    "media.folder.recordings.desc": "Concert performance videos from recital halls in Moscow and beyond.",
    "media.folder.stage.title": "Stage Moments",
    "media.folder.stage.desc": "On-stage photographs from recent recitals and festivals.",
    "media.folder.studio.title": "Portraits & Studio",
    "media.folder.studio.desc": "Portrait sessions and behind-the-scenes moments off stage.",
    "hero.name": "Zijing Zeng",
    "hero.title": "Classical Pianist",
    "about.title": "Biography",
    "about.text": `Zijing Zeng was born in Wuhan in 1997. She started music training at the age of 5. In 2006, Zijing entered the The Attached Primary School of Wuhan Conservatory of Music with Prof. Jian Wang. In 2009, Zijing continued her studies at The Middle School Attached of Wuhan Conservatory of Music with Assoc. Prof. Xian Wang. Since 2013 she also took lessons with Prof. Chun Pan of the Central Conservatory of Music. From 2016, Zijing studied at the Moscow State Tchaikovsky Conservatory in the studio of Prof. Olga Zhukov(Assistant Elenora Karpukhova),and graduated with distinction in 2021. Then she has been an assistant-trainee at Moscow State Tchaikovsky Conservatory in class of Assoc. Prof. Dmitry Kaprin. In 2024 she completed degree Aspirantura with Prof. Alexey Yudin. Now she is studying with pianist Stanislav Korchagin. Zijing currently serves on the Faculty of Arts at Moscow State University.\n\nFrom the age of ten, Zijing has been participating in numerous concerts, competitions, festivals and master classes. Her competition debut was the Second Wuhan Lux Cup Television Piano Competition in 2008. Two years later, she became a laureate at The Third KAWAI Piano Competition in Wuhan. Zijing has won prizes in many competitions, including The Third F. Liszt Piano Competition in Wuhan (2011), second prize at the First Piano Competition at the Wuhan School of Music (2012), first prize at the K. Imola International Competition (Beijing, 2012), the Changjiang Youth Piano Competition (Wuhan, 2014), a Grand Prix winner at the Moscow Open Interregional Music Competition "Islamey" (Moscow, 2019), diploma winner of the 19.Münchner Klavierpodium der Jugend (Munich, 2019), and so on. In July 2013, Zijing was honored to represent China at the International Festival in Italy (r .Imola). In 2022, she was invited to the Glocal Piano Project, and she's also a participant of the 64th Ferruccio Busoni International Piano Competition. In 2023 she participanted in the XVII International Tchaikovsky Competition.\n\nZijing has performed in many prestigious concert halls in Russia, including Great Hall of Moscow Conservatory, House of music. Zeng Zijing is not limited to solo repertoire, but also has a good cooperative relationship with Kirill Rodin, a famous Russian cellist and educator and the gold medal winner of the Tchaikovsky International Competition. As an active participant of the masterclasses, Zijing has worked with such renowned artists such as Vovka Ashkenazi, Vladimir Tropp, Natalia Trull, Alexsander Kobrin, Boris Slutsky, Pavel Nersessian, Stefano Fiuzzi, Stanislav Igolinsky, Philip Kopachevsky. She has been highly praised by masters. The world-renowned pianists Eliso Virsaladze, Vovka Ashkenazi, Vladimir Ovchinnikova, and piano masters Liu Shikun and Li Mingqiang have all given high praise and recognition.\n\nEliso Virsaladze, a master of the Russian school, once commented that "Zijing is a talented pianist who is extremely passionate about classical music and has a serious attitude. In addition to strong emotions and superb skills, this young musician also has the qualities required of a mature master, which is the key to whether a person can become a true musician."`,
    "bio.card1.eyebrow": "Origins",
    "bio.card1.title": "Early Training",
    "bio.card1.text": "Born in Wuhan in 1997, Zijing began piano at the age of five. In 2006 she entered the Primary School attached to the Wuhan Conservatory of Music with Prof. Jian Wang, continuing at the affiliated Middle School with Assoc. Prof. Xian Wang. From 2013 she also studied with Prof. Chun Pan of the Central Conservatory of Music in Beijing.",
    "bio.card2.eyebrow": "Moscow · Faculty",
    "bio.card2.title": "Moscow Conservatory & Teaching",
    "bio.card2.text": "In 2016 she entered the Moscow State Tchaikovsky Conservatory in the studio of Prof. Olga Zhukova (assistant Elenora Karpukhova), graduating with distinction in 2021. She then joined the class of Assoc. Prof. Dmitry Kaprin as assistant-trainee. In 2024 she completed her Aspirantura (candidate degree) under Prof. Alexey Yudin, and now studies with Stanislav Korchagin. Since 2022 she has taught piano at the Faculty of Arts, Moscow State University.",
    "bio.card3.eyebrow": "Laureate",
    "bio.card3.title": "Awards & Competitions",
    "bio.card3.text": "Prize-winner at the Wuhan KAWAI (2010) and Liszt (2011) competitions, First Prize at the K. Imola International Competition in Beijing (2012), and laureate of the Changjiang Youth Piano Competition (2014). In 2019 she won the Grand Prix of the Moscow \"Islamey\" Competition and the Chopin prize at the 19th Münchner Klavierpodium der Jugend. Selected for the Glocal Piano Project (2022), the 64th Busoni Competition, and the XVII International Tchaikovsky Competition (2023).",
    "bio.card4.eyebrow": "Stage",
    "bio.card4.title": "Concerts & Collaborations",
    "bio.card4.text": "Zijing has appeared in leading Russian halls including the Great Hall of the Moscow Conservatory and the House of Music. In July 2013 she was honored to represent China at the Imola International Festival in Italy. Beyond her solo work, she maintains a close chamber partnership with Kirill Rodin — celebrated Russian cellist, pedagogue and gold medallist of the Tchaikovsky Competition.",
    "bio.card5.eyebrow": "Mentors",
    "bio.card5.title": "Masterclasses & Recognition",
    "bio.card5.text": "She has worked in masterclasses with Vovka Ashkenazi, Vladimir Tropp, Natalia Trull, Alexander Kobrin, Boris Slutsky, Pavel Nersessian, Stefano Fiuzzi, Stanislav Igolinsky and Philip Kopachevsky. Her artistry has drawn high praise from Eliso Virsaladze, Vladimir Ovchinnikov and the piano masters Liu Shikun and Li Mingqiang.",
    "bio.quote.text": "Zijing is a talented pianist, extremely passionate about classical music and serious in her approach. Beyond strong emotion and superb technique, this young musician already possesses the qualities of a mature master — the key to whether one can truly become a musician.",
    "bio.quote.author": "— Eliso Virsaladze",
    "schedule.title": "Performance Schedule",
    "gallery.title": "Photo Gallery",
    "performance3.date": "November 5, 2025 19:00",
    "performance3.venue": "Rachmaninoff Hall of the Moscow Conservatory, Bol'shaya Nikitskaya Ulitsa, 11, Moscow",
    "performance3.title": "Beethoven Piano Concerto No.4",
    "performance4.date": "November 2, 2025 15:00",
    "performance4.venue": "Moscow Region, Chekhov Municipal District, Melikhovo Village, A.P. Chekhov Museum-Reserve, Building 1",
    "performance4.title": "Beethoven Piano Sonata No.18, Beethoven Violin Sonata No.4",
    "performance5.date": "November 15, 2025 17:00",
    "performance5.venue": "Ulitsa Bol'shaya Ordynka, Building 6/2, 1, Dom Rachmaninoff, Moscow",
    "performance5.title": "Bach Prelude and Fugue D major BWV 874",
    "performance6.date": "January 31, 2026 14:00",
    "performance6.venue": "Moscow Region, Chekhov Municipal District, Melikhovo Village, A.P. Chekhov Museum-Reserve, Building 1",
    "performance6.title": "S. Rachmaninoff, F. Liszt, A. Scriabin",
    "performance7.date": "February 14, 2026 17:00",
    "performance7.venue": "Nikolo-Yamskaya St., 1, Moscow",
    "performance7.title": "Jianzhong Wang - Silver Clouds Chasing The Moon",
    "performance8.date": "March 28, 2026 14:00",
    "performance8.venue": "Moscow Region, Chekhov Municipal District, Melikhovo Village, A.P. Chekhov Museum-Reserve, Building 1",
    "performance8.title": "S. Rachmaninoff, F. Liszt",
    "performance9.date": "July 20, 2025 17:30",
    "performance9.venue": "Verbrugghen Hall, Sydney Conservatorium of Music, 1 Conservatorium Rd, NSW 2000, Sydney, Australia",
    "performance9.title": "Piano Recital",
    "performance10.date": "July 28, 2025 19:00",
    "performance10.venue": "Concert hall Maltese Chapel, Sadovaya Street, 26, Saint Petersburg, Russia",
    "performance10.title": "Piano Recital",
    "performance11.date": "July 30, 2025 19:00",
    "performance11.venue": "Rachmaninoff Hall of the Moscow Conservatory, Bol'shaya Nikitskaya Ulitsa, 11, Moscow, Russia",
    "performance11.title": "Piano Recital",
    "contact.title": "Contact",
    "contact.phone": "Phone",
    "contact.social": "Social Media",
    "video.title": "Performance Videos",
    "invitation.greeting": "Welcome to My World",
    "invitation.subtitle": "Devoted to Classical Music",
    "invitation.text": "Music is the language of the soul. Every note carries emotion, every phrase tells a story. I invite you to share in the beauty of classical music — a timeless art that transcends boundaries and speaks to the heart.",
    "invitation.signature": "— Zijing Zeng",
    "quote.text": "Music is the silence between the notes.",
    "quote.author": "— Claude Debussy",
    "filter.country": "Country",
    "filter.city": "City",
    "filter.all": "All",
    "filter.results": "concerts shown",
    "filter.empty": "No concerts match the selected filters.",
    "country.russia": "Russia",
    "country.australia": "Australia",
    "city.moscow": "Moscow",
    "city.moscow_region": "Moscow Region",
    "city.saint_petersburg": "Saint Petersburg",
    "city.sydney": "Sydney",
    "bio.dialog.hint": "Click to read more",
    "bio.dialog.summary_label": "Summary",
    "bio.dialog.full_label": "Full biography",
    "bio.dialog.source_label": "Source",
    "bio.dialog.source_text": "Compiled from the artist's official biography and public performance records. Content provided and verified by Zijing Zeng."
  },
  ru: {
    "nav.home": "Главная",
    "nav.about": "О себе",
    "nav.schedule": "Расписание",
    "nav.gallery": "Галерея",
    "nav.media": "Медиатека",
    "nav.contact": "Контакты",
    "media.title": "Медиатека",
    "media.back": "Назад в библиотеку",
    "media.videos": "видео",
    "media.photos": "фото",
    "media.open": "Открыть папку",
    "media.playlist": "Плейлист",
    "media.folder.recordings.title": "Живые записи",
    "media.folder.recordings.desc": "Видеозаписи концертных выступлений в залах Москвы и за её пределами.",
    "media.folder.stage.title": "Моменты на сцене",
    "media.folder.stage.desc": "Фотографии со сцены недавних концертов и фестивалей.",
    "media.folder.studio.title": "Портреты и студия",
    "media.folder.studio.desc": "Портретные съёмки и закулисные моменты вне сцены.",
    "hero.name": "Цзыцзин Цзэн",
    "hero.title": "Пианист-классик",
    "about.title": "Биография",
    "about.text": `Цзыцзин Цзэн родилась в 1997 году в Китае. С пяти лет начала играть на фортепиано, с десяти— участвовать в концертах, конкурсах, фестивалях и мастер-классах. Обучалась в музыкальной школе при Уханьской консерватории в классе доцента Ван Сьяна. С 2013 года началась заниматься с профессором Пан Чун. В 2021 году с отличием закончила Московскую консерваторию по классу фортепиано профессора О.М.Жуковой( ассистент Э.А.Карпуховая), а затем поступила в аспирантуру в класс доцента Д.А. Каприна. В настоящее время подготовкой диссертационного исследования руководит доктор педагогических наук, профессор А.П.Юдин и занимается с известным пианистом Станиславом Корчагином. С 2022 года Цзыцзин работает преподавателем по фортепиано на факультете искусств МГУ имени М. В. Ломоносова.\n\nВ 2012 году победила на Международном конкурсе имени К. Имола (Китай), и представляла КНРна Международном фестивале в Имоле (Италия). В 2019 году завоевала «Гран-при» на конкурсе «Исламей» (Россия), в том же году победила на конкурсе 19-го Münchner Klavierpodium der Jugend в Мюнхене (Германия). В 2021 году получила I премию на конкурсе-фестивале VII «Allegretto Grazioso» (Россия). В 2022 году пианистку пригласили в программу Glocal Piano Project, также является участницей 64-го Международного конкурса пианистов Ф. Бузони (Италия). В 2023 году стала участницей XVI Международного конкурса имени П. И. Чайковского в Москве.\n\nВыступления пианистки проходили во многих залах мира, среди которых — Большой зал Московской консерватории, Концертный зал в Хайнане и другие. Не ограничиваясь сольными программами, пианистка имеет большой опыт работы в камерном ансамбле — в партнерстве с мастером — виолончелистом Кириллом Родиным. Вместе с ним гастролировала по Китаю в 2024 году.\n\nПринимала участие в мастер-классах таких педагогов, как Вовка Ашкенази, Владимир Тропп, Наталья Трулль, Александр Кобрин, Борис Слуцкий, Павел Нерсесьян, Стефано Фьюцци, Станислав Иголинский и Филипп Копачевский. Она получила высокую оценку от мастеров. Всемирно известные пианисты, такие как Элисо Вирсаладзе, Владимир Овчинников, Лю Шикунь и Ли Минцян, дали ей высокую оценку и признание.\n\nЭлисо Вирсаладзе, корифей русской школы, однажды заметила, что «Цзыцзин — талантливая пианистка, которая чрезвычайно увлечена классической музыкой и имеет серьезное отношение к музыке. Помимо сильных эмоций и великолепных навыков, этот молодой музыкант также обладает качествами, требуемыми от зрелого мастера, что является ключом к тому, может ли человек стать настоящим музыкантом».`,
    "bio.card1.eyebrow": "Истоки",
    "bio.card1.title": "Ранние годы",
    "bio.card1.text": "Родилась в Ухане в 1997 году, начала заниматься фортепиано с пяти лет. В 2006 году поступила в начальную школу при Уханьской консерватории в класс профессора Ван Цзянь, продолжила обучение в средней школе при консерватории у доцента Ван Сяня. С 2013 года также занималась с профессором Пан Чунь Центральной консерватории (Пекин).",
    "bio.card2.eyebrow": "Москва · Преподавание",
    "bio.card2.title": "Московская консерватория и МГУ",
    "bio.card2.text": "В 2016 году поступила в МГК им. П. И. Чайковского в класс профессора О. М. Жуковой (ассистент Э. А. Карпухова), окончила с отличием в 2021 году. Затем — ассистент-стажёр в классе доцента Д. А. Каприна. В 2024 году завершила аспирантуру под руководством профессора А. П. Юдина, в настоящее время занимается с пианистом Станиславом Корчагиным. С 2022 года преподаёт фортепиано на факультете искусств МГУ им. М. В. Ломоносова.",
    "bio.card3.eyebrow": "Лауреат",
    "bio.card3.title": "Награды и конкурсы",
    "bio.card3.text": "Лауреат уханьских конкурсов KAWAI (2010) и им. Ф. Листа (2011), обладатель первой премии Международного конкурса им. К. Имолы (Пекин, 2012), лауреат Чанцзянского юношеского конкурса (2014). В 2019 году — Гран-при московского конкурса «Исламей» и премия Шопена на 19-м Münchner Klavierpodium der Jugend. Приглашена в Glocal Piano Project (2022), участница 64-го конкурса им. Ф. Бузони и XVII Международного конкурса им. П. И. Чайковского (2023).",
    "bio.card4.eyebrow": "Сцена",
    "bio.card4.title": "Концерты и сотрудничество",
    "bio.card4.text": "Выступала в ведущих российских залах, включая Большой зал Московской консерватории и Дом музыки. В июле 2013 года представляла Китай на Международном фестивале в Имоле (Италия). Помимо сольного репертуара, ведёт постоянное камерное сотрудничество с Кириллом Родиным — выдающимся российским виолончелистом, педагогом и золотым медалистом конкурса им. П. И. Чайковского.",
    "bio.card5.eyebrow": "Наставники",
    "bio.card5.title": "Мастер-классы и признание",
    "bio.card5.text": "Занималась на мастер-классах у Вовки Ашкенази, Владимира Троппа, Натальи Трулль, Александра Кобрина, Бориса Слуцкого, Павла Нерсесьяна, Стефано Фьюцци, Станислава Иголинского и Филиппа Копачевского. Её игру высоко оценили Элисо Вирсаладзе, Владимир Овчинников, а также мастера фортепиано Лю Шикунь и Ли Минцян.",
    "bio.quote.text": "Цзыцзин — талантливая пианистка, чрезвычайно увлечённая классической музыкой и очень серьёзная в работе. Помимо сильных эмоций и великолепной техники, этот молодой музыкант уже обладает качествами зрелого мастера — тем, что определяет, сможет ли человек стать настоящим музыкантом.",
    "bio.quote.author": "— Элисо Вирсаладзе",
    "schedule.title": "Расписание выступлений",
    "gallery.title": "Фотогалерея",
    "performance3.date": "5 ноября 2025 19:00",
    "performance3.venue": "Рахманиновский зал Московской консерватории, Большая Никитская улица, 11, Москва",
    "performance3.title": "Концерт №4 для фортепиано с оркестром Бетховена",
    "performance4.date": "2 ноября 2025 15:00",
    "performance4.venue": "Московская область, Чеховский муниципальный район, село Мелихово, Музей-заповедник А.П. Чехова, строение 1",
    "performance4.title": "Бетховен - Соната для фортепиано №18, Бетховен - Соната для скрипки №4",
    "performance5.date": "15 ноября 2025 17:00",
    "performance5.venue": "Улица Большая Ордынка, дом 6/2, строение 1, Дом Рахманинова, Москва",
    "performance5.title": "Бах - Прелюдия и фуга ре мажор BWV 874",
    "performance6.date": "31 января 2026 14:00",
    "performance6.venue": "Московская область, Чеховский муниципальный район, село Мелихово, Музей-заповедник А.П. Чехова, строение 1",
    "performance6.title": "С. Рахманинов, Ф. Лист, А. Скрябин",
    "performance7.date": "14 февраля 2026 17:00",
    "performance7.venue": "Николо-Ямская ул., 1, Москва",
    "performance7.title": "Ван Цзяньчжун - Серебряные облака, преследующие луну",
    "performance8.date": "28 марта 2026 14:00",
    "performance8.venue": "Московская область, Чеховский муниципальный район, село Мелихово, Музей-заповедник А.П. Чехова, строение 1",
    "performance8.title": "С. Рахманинов, Ф. Лист",
    "performance9.date": "20 июля 2025 17:30",
    "performance9.venue": "Зал Вербрюггена, Консерватория Сиднея, 1 Conservatorium Rd, NSW 2000, Сидней, Австралия",
    "performance9.title": "Фортепианный рецитал",
    "performance10.date": "28 июля 2025 19:00",
    "performance10.venue": "Концертный зал Мальтийская часовня, Садовая улица, 26, Санкт-Петербург, Россия",
    "performance10.title": "Фортепианный рецитал",
    "performance11.date": "30 июля 2025 19:00",
    "performance11.venue": "Рахманиновский зал Московской консерватории, Большая Никитская улица, 11, Москва, Россия",
    "performance11.title": "Фортепианный рецитал",
    "contact.title": "Контакты",
    "contact.phone": "Телефон",
    "contact.social": "Социальные сети",
    "video.title": "Видео выступлений",
    "invitation.greeting": "Добро пожаловать в мой мир",
    "invitation.subtitle": "Преданность классической музыке",
    "invitation.text": "Музыка — это язык души. Каждая нота несёт в себе эмоцию, каждая фраза рассказывает историю. Я приглашаю вас разделить красоту классической музыки — вечного искусства, которое преодолевает границы и говорит с сердцем.",
    "invitation.signature": "— Цзыцзин Цзэн",
    "quote.text": "Музыка — это тишина между нотами.",
    "quote.author": "— Клод Дебюсси",
    "filter.country": "Страна",
    "filter.city": "Город",
    "filter.all": "Все",
    "filter.results": "концертов показано",
    "filter.empty": "Нет концертов, соответствующих выбранным фильтрам.",
    "country.russia": "Россия",
    "country.australia": "Австралия",
    "city.moscow": "Москва",
    "city.moscow_region": "Московская область",
    "city.saint_petersburg": "Санкт-Петербург",
    "city.sydney": "Сидней",
    "bio.dialog.hint": "Нажмите, чтобы узнать больше",
    "bio.dialog.summary_label": "Кратко",
    "bio.dialog.full_label": "Полная биография",
    "bio.dialog.source_label": "Источник",
    "bio.dialog.source_text": "Составлено на основе официальной биографии артистки и открытых сведений о концертах. Материал предоставлен и проверен Цзыцзин Цзэн."
  },
  zh: {
    "nav.home": "首页",
    "nav.about": "关于我",
    "nav.schedule": "演出日程",
    "nav.gallery": "演出记录",
    "nav.media": "媒体库",
    "nav.contact": "联系方式",
    "media.title": "媒体库",
    "media.back": "返回媒体库",
    "media.videos": "视频",
    "media.photos": "照片",
    "media.open": "打开文件夹",
    "media.playlist": "播放列表",
    "media.folder.recordings.title": "现场录像",
    "media.folder.recordings.desc": "莫斯科等地音乐厅的现场演出视频合集。",
    "media.folder.stage.title": "舞台瞬间",
    "media.folder.stage.desc": "近期音乐会及音乐节的舞台演出照片。",
    "media.folder.studio.title": "肖像与工作室",
    "media.folder.studio.desc": "肖像拍摄与舞台之外的幕后时刻。",
    "hero.name": "曾子荆",
    "hero.title": "古典钢琴家",
    "about.title": "个人简介",
    "about.text": `曾子荆，五岁开始学习钢琴，九岁以第二名的成绩考入武汉音乐学院附小师从王健教授，随后进入武汉音乐学院附中师从王暹副教授。自2013年起跟随中央音乐学院钢琴系教授潘淳学习。十八岁同时以优异的成绩考取了上海音乐学院钢琴系和世界顶尖音乐学府莫斯科国立柴科夫斯基音乐学院，2015年曾子荆选择赴俄深造，于2021年以全优成绩毕业，取得钢琴表演、室内乐、声乐艺术指导和教育学四个专业的硕士学位文凭，同时也是Alexander Goldenweiser学派传人Olga Zhukova教授的关门弟子。二十三岁前往莫斯科国立师范大学师从Alexey Yudin教授研修博士学位，同时以第一名的成绩考入莫斯科国立柴可夫斯基音乐学院成为俄罗斯钢琴大师、苏联功勋艺术家Eliso Virsaladze助教Dmitry Kaprin的第一位演奏博士。2024 年她在 Alexey Yudin 教授的指导下完成了副博士学位。2022年11月，正式入职莫斯科国立大学艺术系任教，担任钢琴主科老师。\n\n获奖记录：\n\n2013年在第二届意大利伊莫拉卡索尼国际钢琴比赛中，作为青年A组年龄最小的选手，荣获中国区选拔赛北京总决赛第一名。同年受邀赴意大利参加伊莫拉夏季国际钢琴音乐节，在当地成功举行演出。2014年在纪念中国钢琴作品��年展"大音"杯全国邀请赛中荣获青年B组（专业）一等奖。同年在第七届上海青少年钢琴大赛中获专业青年组一等奖。2015年在"长江钢琴杯"青少年钢琴比赛中获奖。2019年参加德国慕尼黑"Münchner Klavierpodium"钢琴比赛，荣获肖邦奖，并受邀在颁奖典礼上演出。同年12月摘得莫斯科"伊斯拉美"音乐家大奖赛特等奖，并受邀在颁奖典礼上演出。2020年在"Best Composers"最佳舒曼作品比赛中荣获第一名。同年在莫斯科国际弗拉基米尔·克雷涅夫钢琴比赛中获优秀演奏奖。2021年获莫斯科国际艺术音乐节第一名。同年成为第三届The Weatherford College International Piano Competition决赛选手。2022年入围布索尼国际钢琴比赛，成为全球100名Glocal Piano Project钢琴家之一。2023年入围SIPC新加坡国际钢琴比赛。同年入围第十七届柴可夫斯基国际钢琴比赛。\n\n曾子荆足迹遍及欧洲，俄罗斯，中国等地，并多次在柴可夫斯基音乐学院大厅，小厅等地举办独奏音乐会，均获好评。曾子荆不仅限于独奏曲目，与俄罗斯著名大提琴家、教育家柴可夫斯基国际比赛金奖得主Kirill Rodin也有着良好的合作关系。\n\n近年来，曾子荆也积极参加国内外的大师班学习，如Vovka Ashkenazi, Vladimir Tropp, Natalia Trull, Alexsander Kobrin, Boris Slutsky, Pavel Nersessian, Stefano Fiuzzi, Stanislav Igolinsky, Philip Kopachevsky等，并受到大师们的一致高度赞赏。享誉世界国际乐坛上著名钢琴家Eliso Virsaladze、Vovka Ashkenazi，Vladimir Ovchinnikova以及钢琴泰斗刘诗昆、李名强先生都曾给予了高度评价与认可。\n\n俄罗斯学派巨匠艾利索·维萨拉兹曾评价"曾子荆是一位对古典音乐极度热爱并有着认真态度的才华横溢的钢琴家，这位年轻的音乐家除了拥有强烈的情感和精湛的技巧外，还具备了一个成熟大师所需要的品质，这是一个人能否成为真正的音乐家的关键。"`,
    "bio.card1.eyebrow": "启蒙",
    "bio.card1.title": "早年学琴",
    "bio.card1.text": "1997年出生于武汉，五岁开始学习钢琴。2006年考入武汉音乐学院附小，师从王健教授；随后进入武汉音乐学院附中，师从王暹副教授。2013年起，跟随中央音乐学院钢琴系潘淳教授学习。",
    "bio.card2.eyebrow": "莫斯科 · 教学",
    "bio.card2.title": "柴院深造与莫大任教",
    "bio.card2.text": "2016年考入莫斯科国立柴可夫斯基音乐学院，师从Olga Zhukova教授（助教Elenora Karpukhova），2021年以全优成绩毕业。此后作为助教研修生跟随Dmitry Kaprin副教授学习。2024年，在Alexey Yudin教授指导下完成副博士（Аспирантура）学位，目前跟随钢琴家Stanislav Korchagin深造。2022年起于莫斯科国立大学艺术系任钢琴主科教师。",
    "bio.card3.eyebrow": "殊荣",
    "bio.card3.title": "比赛与奖项",
    "bio.card3.text": "武汉KAWAI钢琴比赛（2010）、李斯特钢琴比赛（2011）获奖者；2012年获北京K. Imola国际钢琴比赛第一名；2014年长江钢琴杯青少年比赛获奖。2019年荣获莫斯科「伊斯拉美」音乐家大奖赛特等奖，同年获第19届慕尼黑Münchner Klavierpodium der Jugend肖邦奖。2022年入选Glocal Piano Project；入围第64届布索尼国际钢琴比赛及第十七届柴可夫斯基国际钢琴比赛（2023）。",
    "bio.card4.eyebrow": "舞台",
    "bio.card4.title": "演出与合作",
    "bio.card4.text": "曾登台众多俄罗斯顶级音乐厅，包括莫斯科音乐学院大厅与音乐之家。2013年7月受邀代表中国出席意大利伊莫拉国际音乐节。除独奏曲目外，与俄罗斯著名大提琴家、教育家、柴可夫斯基国际比赛金奖得主Kirill Rodin保持长期室内乐合作。",
    "bio.card5.eyebrow": "师承",
    "bio.card5.title": "大师班与业界认可",
    "bio.card5.text": "曾参加Vovka Ashkenazi、Vladimir Tropp、Natalia Trull、Alexander Kobrin、Boris Slutsky、Pavel Nersessian、Stefano Fiuzzi、Stanislav Igolinsky、Philip Kopachevsky等名家大师班。享誉国际的钢琴家Eliso Virsaladze、Vladimir Ovchinnikov及钢琴泰斗刘诗昆、李名强先生均给予高度评价与认可。",
    "bio.quote.text": "曾子荆是一位对古典音乐极度热爱、态度极为认真的才华横溢的钢琴家。除了强烈的情感和精湛的技巧外，这位年轻音乐家已具备一位成熟大师所必需的品质——这正是决定一个人能否成为真正音乐家的关键。",
    "bio.quote.author": "— 艾利索·维萨拉兹",
    "schedule.title": "演出安排",
    "gallery.title": "演出记录",
    "performance3.date": "2025年11月5日 19:00",
    "performance3.venue": "莫斯科音乐学院拉赫马尼诺夫音乐厅，大尼基茨卡娅街，11号，莫斯科",
    "performance3.title": "贝多芬第四钢琴协奏曲",
    "performance4.date": "2025年11月2日 15:00",
    "performance4.venue": "莫斯科州契诃夫市梅利霍沃村，契诃夫博物馆保护区，1号楼",
    "performance4.title": "贝多芬第18钢琴奏鸣曲，贝多芬第4小提琴奏鸣曲",
    "performance5.date": "2025年11月15日 17:00",
    "performance5.venue": "莫斯科大奥尔登卡街6/2号楼1，拉赫马尼诺夫故居",
    "performance5.title": "巴赫D大调前奏曲与赋格 BWV 874",
    "performance6.date": "2026年1月31日 14:00",
    "performance6.venue": "莫斯科州契诃夫市梅利霍沃村，契诃夫博物馆保护区，1号楼",
    "performance6.title": "拉赫玛尼诺夫、李斯特、斯克里亚宾作品",
    "performance7.date": "2026年2月14日 17:00",
    "performance7.venue": "莫斯科尼科洛-雅姆斯卡亚街1号",
    "performance7.title": "王建中 - 彩云追月",
    "performance8.date": "2026年3月28日 14:00",
    "performance8.venue": "莫斯科州契诃夫市梅利霍沃村，契诃夫博物馆保护区，1号楼",
    "performance8.title": "拉赫玛尼诺夫、李斯特",
    "performance9.date": "2025年7月20日 17:30",
    "performance9.venue": "悉尼音乐学院维布鲁根音乐厅，悉尼音乐学院路1号，新南威尔士州2000，悉尼，澳大利亚",
    "performance9.title": "钢琴独奏音乐会",
    "performance10.date": "2025年7月28日 19:00",
    "performance10.venue": "圣彼得堡马尔他礼拜堂音乐厅，花园街26号，圣彼得堡，俄罗斯",
    "performance10.title": "钢琴独奏音乐会",
    "performance11.date": "2025年7月30日 19:00",
    "performance11.venue": "莫斯科音乐学院拉赫马尼诺夫音乐厅，大尼基茨卡娅街11号，莫斯科，俄罗斯",
    "performance11.title": "钢琴独奏音乐会",
    "contact.title": "联系方式",
    "contact.phone": "电话",
    "contact.social": "社交媒体",
    "video.title": "演出视频",
    "invitation.greeting": "欢迎来到我的世界",
    "invitation.subtitle": "专注于古典音乐",
    "invitation.text": "音乐是灵魂的语言。每一个音符承载着情感，每一个乐句诉说着故事。我诚挚地邀请您一同感受古典音乐之美——这门超越时空、直抵心灵的永恒艺术。",
    "invitation.signature": "— 曾子荆",
    "quote.text": "音乐，是音符之间的静默。",
    "quote.author": "— 克劳德·德彪西",
    "filter.country": "国家",
    "filter.city": "城市",
    "filter.all": "全部",
    "filter.results": "场演出",
    "filter.empty": "没有符合筛选条件的演出。",
    "country.russia": "俄罗斯",
    "country.australia": "澳大利亚",
    "city.moscow": "莫斯科",
    "city.moscow_region": "莫斯科州",
    "city.saint_petersburg": "圣彼得堡",
    "city.sydney": "悉尼",
    "bio.dialog.hint": "点击查看详情",
    "bio.dialog.summary_label": "摘要",
    "bio.dialog.full_label": "完整介绍",
    "bio.dialog.source_label": "来源说明",
    "bio.dialog.source_text": "内容整理自艺术家提供的官方个人简历及公开演出记录，已由曾子荆本人核实。"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
